FROM container-registry.oracle.com/graalvm/native-image:17-muslib

COPY ./target/demo-0.0.1-SNAPSHOT.jar /build/
WORKDIR /build
RUN native-image --static -jar demo-0.0.1-SNAPSHOT.jar -J-Xmx7g -J-Xms7g -H:Name=demo

